title: Placeholder page title
description: A starter page for something
theme: just-the-docs

url: https://petukkas.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
